database:
  url: "jdbc:mysql://localhost:3306/athenarank"
  username: archer
  password: guest

leaderboard:
  enabled: false
  heads:
  - "0,0,0"
  - "0,0,0"
  - "0,0,0"
  signs:
  - "0,0,0"
  - "0,0,0"
  - "0,0,0"